### ISSUE TITLE
About train loss

### ISSUE THREAD

**Issue by wh7776** [ductuantruong/mfa_conformer_sv#1]
Hello, I noticed that you achieved an impressive EER of 0.72%. I attempted training with similar hyperparameters on a single Nvidia 4090, but my accuracy was only 0.84 with a loss of approximately 0.5. I would appreciate it if you could kindly share the value of your loss after training convergence.

**Comment by ductuantruong** [comment]
Hi, I got something like this:
`
Epoch 17: 100%|█████████▉| 10908/10912 [29:32<00:00,  6.15it/s, loss=0.508, v_num=3247829, train_loss=0.722, acc=86.30]
cosine EER: 0.72% with threshold 0.278 [01:05<00:00, 70.34it/s]
`
This result is from training with A100 GPU. As mentioned in the original repo, different GPU device may lead to different results. I have encountered this when training the model with A40 GPU and A100 GPU.
